[package]
name = "myperlinnoise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.9"
num-complex = "0.4.5"
rand = "0.8.5"
show-image = "0.13.1"
